#################
## Development ##
#################

#specify the base image
FROM node:16-alpine AS development

# set the needed env variables
ARG NODE_ENV=dev
ENV NODE_ENV=${NODE_ENV}

#specify the working directory inside the container
WORKDIR /usr/app

#copying package.josn & packag-lock.json inside the container working directory
COPY package*.json ./

#install dependencies inside the container
RUN npm install

COPY . . 

# start the app in dev mode
RUN npm run build

EXPOSE 5000


#################
## Production ###
#################

# specify the base image
FROM node:16-alpine as production

# set the needed env variables
ARG NODE_ENV=prod
ENV NODE_ENV=${NODE_ENV}

#specify the working directory inside the container
WORKDIR /usr/app

# copy the compiled code from the development stage
COPY --from=development /usr/auth/src .

EXPOSE 5000

CMD ["NODE_TLS_REJECT_UNAUTHORIZED=0",  "node", "dist/src/main"]